"""
Helper class for publishing skills to the Connex Registry.
"""

import os
import json
import httpx
from typing import Dict, Any, Optional

from agi.config import AGIConfig


class SkillPublisher:
    """
    Handles the details of creating skill manifests and publishing to the registry.
    """
    
    def __init__(self, config: AGIConfig):
        self.config = config
        
    async def publish_skill(
        self, 
        name: str, 
        code: str, 
        description: str,
        files: Optional[Dict[str, str]] = None,
        category: str = "utilities"
    ) -> Dict[str, Any]:
        """
        Publish a new skill to the registry.
        
        Args:
            name: Scoped name (@user/skill)
            code: Python implementation code
            description: Short description
            files: Additional files (e.g. SKILL.md)
            category: Skill category
            
        Returns:
            API response from registry
        """
        if not self.config.allow_skill_publishing:
            raise PermissionError("Skill publishing is disabled in AGI configuration")
            
        if not self.config.connex_auth_token:
            raise ValueError("CONNEX_AUTH_TOKEN is required for publishing")
        
        # Parse username from scoped name
        if not name.startswith("@") or "/" not in name:
            raise ValueError("Name must be in format @username/skillname")
            
        username = name.split("/")[0][1:]
        
        # Create manifest structure
        manifest = {
            "name": name,
            "version": "0.1.0",
            "description": description,
            "author": {
                "username": username
            },
            "license": "MIT",
            "keywords": ["agi-generated"],
            "category": category,
            "main": "agent.py",  # Standard entry point
            "capabilities": {
                "tools": []
            },
            "runtime": {
                "python": ">=3.10",
                "timeout": 30,
                "memory": 512
            },
            "implementationCode": code,
            "files": {
                "README.md": f"# {name}\n\n{description}\n\nGenerated by Connex AGI."
            },
            "private": False
        }
        
        if files:
            manifest["files"].update(files)
        
        # Publish via API
        url = f"{self.config.registry_url}/skills"
        headers = {
            "Authorization": f"Bearer {self.config.connex_auth_token}",
            "Content-Type": "application/json"
        }
        
        async with httpx.AsyncClient() as client:
            response = await client.post(
                url, 
                json={"manifest": manifest},
                headers=headers,
                timeout=30.0
            )
            
            if response.status_code not in (200, 201):
                raise Exception(f"Registry error ({response.status_code}): {response.text}")
                
            return response.json()
