"""
Unified publisher for Connex components (Skills, Reflexes, Perceptions).
"""

import os
import json
import httpx
import inspect
from typing import Dict, Any, Optional, Union, List

from agi.config import AGIConfig
from agi.skilldock.base import Skill
from agi.reflex.base import ReflexModule
from agi.perception.base import PerceptionModule


class ConnexPublisher:
    """
    Handles the details of creating component manifests and publishing to the registry.
    Support Skills, Reflexes, and Perceptions.
    """
    
    def __init__(self, config: AGIConfig):
        self.config = config
        
    async def publish_component(
        self, 
        component: Union[Skill, ReflexModule, PerceptionModule],
        scoped_name: str,
        code: Optional[str] = None,
        files: Optional[Dict[str, str]] = None,
        private: bool = False
    ) -> Dict[str, Any]:
        """
        Publish a component to the registry.
        
        Args:
            component: The instance of the component to publish
            scoped_name: Name in format @user/name
            files: Additional files to include (will include the source file automatically)
            private: Whether to mark as private
            
        Returns:
            API response from registry
        """
        if not self.config.allow_skill_publishing:
            raise PermissionError("Publishing is disabled in AGI configuration")
            
        if not self.config.connex_auth_token:
            raise ValueError("CONNEX_AUTH_TOKEN is required for publishing")
        
        # Parse username from scoped name
        if not scoped_name.startswith("@") or "/" not in scoped_name:
            raise ValueError("Name must be in format @username/component_name")
            
        username = scoped_name.split("/")[0][1:]
        
        # Get source code
        if not code:
            try:
                source_file = inspect.getfile(component.__class__)
                with open(source_file, "r", encoding="utf-8") as f:
                    code = f.read()
                main_filename = os.path.basename(source_file)
            except Exception as e:
                raise ValueError(f"Could not read source code for component: {e}")
        else:
            main_filename = "agent.py" # Default if provided explicitly

        # Determine type
        if isinstance(component, Skill):
            comp_type = "skill"
            meta = component.metadata
            category = meta.category
        elif isinstance(component, ReflexModule):
            comp_type = "reflex"
            meta = component.metadata
            category = getattr(meta, "trigger_type", "event")
        elif isinstance(component, PerceptionModule):
            comp_type = "perception"
            meta = component.metadata
            category = getattr(meta, "category", "general")
        else:
            raise ValueError("Unknown component type")

        # Create manifest structure
        manifest = {
            "name": scoped_name,
            "type": comp_type,
            "version": getattr(meta, "version", "0.1.0"),
            "description": meta.description,
            "author": {
                "username": username
            },
            "license": "MIT",
            "keywords": ["agi-generated", comp_type],
            "category": category,
            "main": main_filename,
            "implementationCode": code,
            "files": {
                "README.md": f"# {scoped_name}\n\n{meta.description}\n\nGenerated by Connex AGI."
            },
            "private": private
        }
        
        # Add component specific metadata
        if comp_type == "skill":
            manifest["capabilities"] = {
                "input_schema": meta.input_schema,
                "output_schema": meta.output_schema
            }
        elif comp_type == "reflex":
            manifest["capabilities"] = {
                "trigger_type": meta.trigger_type
            }
        
        if meta.config_schema:
             manifest["config_schema"] = meta.config_schema

        if files:
            manifest["files"].update(files)
        
        # Publish via API
        endpoint = f"{comp_type}s" # skills, reflexes, perceptions
        url = f"{self.config.registry_url}/{endpoint}"
        headers = {
            "Authorization": f"Bearer {self.config.connex_auth_token}",
            "Content-Type": "application/json"
        }
        
        async with httpx.AsyncClient() as client:
            response = await client.post(
                url, 
                json={"manifest": manifest},
                headers=headers,
                timeout=30.0
            )
            
            if response.status_code not in (200, 201):
                raise Exception(f"Registry error ({response.status_code}): {response.text}")
                
            return response.json()
