import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen bg-neutral-900 text-white`}
      >
        {/* Sidebar */}
        <nav className="w-64 border-r border-neutral-800 p-4 flex flex-col gap-4">
          <div className="font-bold text-xl mb-4 px-2 bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
            Connex AGI
          </div>

          <a href="/" className="px-4 py-2 hover:bg-neutral-800 rounded-lg transition-colors flex items-center gap-2">
            <span>💬</span> Chat
          </a>
          <a href="/skills" className="px-4 py-2 hover:bg-neutral-800 rounded-lg transition-colors flex items-center gap-2">
            <span>🧩</span> Skills
          </a>
          <a href="/history" className="px-4 py-2 hover:bg-neutral-800 rounded-lg transition-colors flex items-center gap-2">
            <span>📜</span> History
          </a>
        </nav>

        {/* Main Content */}
        <main className="flex-1 overflow-auto p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
